version: '3.2'
services:
  postgresql:
    build: .
    ports:
      - 5433:5432
    container_name: spring-postgres
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    tty: true
    volumes:
      - ./init_db:/docker-entrypoint-initdb.d
      - $HOME/Dev/Docker/vscode-remote/vscode-remote-postgres:/workspaces
    networks:
      - remote-container_common-network

networks:
  remote-container_common-network:
    external: true